debugging

diff --git a/.github/workflows/graph.yml b/.github/workflows/graph.yml
--- a/.github/workflows/graph.yml
+++ b/.github/workflows/graph.yml
@@ -63,26 +63,25 @@ jobs:
           name: nvidia.svg
           path: profile/nvidia.svg
 
-      - name: Update Graphs inside repository.
+      - name: Update svg graphs inside repository.
         run: |
           echo on
           git config --global user.name  "gnuplot"
           git config --global user.email "gnuplot@gnuplot.gnuplot"
           git add profile/intel.svg
           git add profile/nvidia.svg
-          git status
-          find .
-          pwd
+          set +e  # Grep succeeds with nonzero exit codes to show results.
+          git status | grep modified
+          if [ $? -eq 0 ]; then git commit -am "updated on - $(date)" & git push; fi
+          set -e
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-#         git commit -m "updated intel.svg and nvidia.svg"
-#         git push
 
-
-# refrences:
+# notes:
 # "u 1:2" is shorthand for "using 1:2"
 # "w lines" is shorthand for "with lines"
+# references:
 # https://gnuplot.sourceforge.net/demo/layout.html
 # https://gnuplot.sourceforge.net/demo/
 # https://stackoverflow.com/questions/51687096/gnuplot-autotitle-coloumnhead-key-and-datafile-with
