timestamp of graph update

diff --git a/.github/workflows/graph.yml b/.github/workflows/graph.yml
--- a/.github/workflows/graph.yml
+++ b/.github/workflows/graph.yml
@@ -63,19 +63,28 @@ jobs:
           name: nvidia.svg
           path: profile/nvidia.svg
 
-      - name: Update svg graphs inside repository.
+      - name: Update timestamp.
         run: |
-          echo on
-          git config --global user.name  "gnuplot"
-          git config --global user.email "gnuplot@gnuplot.gnuplot"
-          git add profile/intel.svg
-          git add profile/nvidia.svg
-          set +e  # Grep succeeds with nonzero exit codes to show results.
-          git status | grep modified
-          if [ $? -eq 0 ]; then git commit -am "updated on - $(date)" & git push; fi
-          set -e
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            echo $(date +"%Y-%m-%d-T%H.%M.%SZ") >> updated.txt
+
+      - name: Commit & Push changes
+        uses: actions-js/push@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+#     - name: Update svg graphs inside repository.
+#       run: |
+#         echo on
+#         git config --global user.name  "gnuplot"
+#         git config --global user.email "gnuplot@gnuplot.gnuplot"
+#         git add profile/intel.svg
+#         git add profile/nvidia.svg
+#         set +e  # Grep succeeds with nonzero exit codes to show results.
+#         git status | grep modified
+#         if [ $? -eq 0 ]; then git commit -am "updated on - $(date)" & git push; fi
+#         set -e
+#       env:
+#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
 # notes:
